# -*- coding: utf-8 -*-
"""plane.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_gx1Tx5eMxjcvTqM9n2LkZQlfjnI78f
"""

from torchvision import transforms, datasets
from torch.utils.data import DataLoader, Dataset
import kagglehub
import random
from collections import Counter
from PIL import Image
import os
import torch
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.optim as optim
from torchvision.models import resnet50, ResNet50_Weights
import torch.nn as nn
import time
from tqdm import tqdm
import torch.nn.functional as F
from sklearn.metrics import confusion_matrix
import seaborn as sns
from sklearn.utils.class_weight import compute_class_weight



class EarlyStopping:
    def __init__(self, patience=3, restore_best_weights=True):
        self.patience = patience
        self.restore_best_weights = restore_best_weights
        self.best_loss = float('inf')
        self.counter = 0
        self.early_stop = False
        self.best_state = None

    def __call__(self, val_loss, model):
        if val_loss < self.best_loss:
            self.best_loss = val_loss
            if self.restore_best_weights:
                self.best_state = model.state_dict().copy()
            self.counter = 0
        else:
            self.counter += 1
            if self.counter >= self.patience:
                self.early_stop = True
                if self.restore_best_weights and self.best_state is not None:
                    model.load_state_dict(self.best_state)


os.environ["KAGGLEHUB_DOWNLOAD_TIMEOUT"] = "300"

# Download latest version
path = kagglehub.dataset_download("seryouxblaster764/fgvc-aircraft")

print("Path to dataset files:", path)

data_path = os.path.join(path, "fgvc-aircraft-2013b", "fgvc-aircraft-2013b", "data")
print(f"data path: {data_path}")
#dir = NONE

for root, dirs, files in os.walk(path):
  if "variants.txt" in files:
    DATA_DIR = root
    break

#dir = r"C:\Users\USER\.cache\kagglehub\datasets\seryouxblaster764\fgvc-aircraft\versions\2"

all_image_paths = []
class_labels = []
image_sizes = []
corrupt_images = []

print("Starting dataset exploration...")

#indexing

if os.path.exists(data_path):
  with open(os.path.join(data_path, "variants.txt"), 'r') as f:
    unique_classes = sorted([line.strip() for line in f if line.strip()])

class_to_idx = {class_name: idx for idx, class_name in enumerate(unique_classes)}
print(f"Completed: Mapped {len(class_to_idx)} classes to numbers.")

# Transforms

# Choosing 224x224 because it is standard for transfer learning backbones (ResNet, MobileNet, etc.)
idx_to_class = {idx: class_name for class_name, idx in class_to_idx.items()}

IMAGE_SIZE = (224, 224)
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

train_transforms = transforms.Compose([
    transforms.Resize(IMAGE_SIZE),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD)
])

val_transforms = transforms.Compose([
    transforms.Resize(IMAGE_SIZE),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD)
])
print("Complete: Transform parameters defined.")

# Create Datasets


class FGVCAircraftDataset(Dataset):
    def __init__(self, data_dir, split_file, class_to_idx, transform=None):
        self.images_dir = os.path.join(data_dir, "images")
        self.transform = transform
        self.image_labels = []

        with open(os.path.join(data_dir, split_file), 'r') as f:
            for line in f:
                if line.strip():
                    img_id, class_name = line.strip().split(' ', 1)
                    self.image_labels.append((f"{img_id}.jpg", class_to_idx[class_name]))

    def __len__(self): return len(self.image_labels)
    def __getitem__(self, idx):
        img_name, label = self.image_labels[idx]
        image = Image.open(os.path.join(self.images_dir, img_name)).convert("RGB")
        if self.transform:
          image = self.transform(image)
        return image, label

# Initialize them
train_dataset = FGVCAircraftDataset(DATA_DIR, "images_variant_train.txt", class_to_idx, transform=train_transforms)
val_dataset = FGVCAircraftDataset(DATA_DIR, "images_variant_val.txt", class_to_idx, transform=val_transforms)

print(f"Train Complete: {len(train_dataset)} images | Val: {len(val_dataset)} images")

BATCH_SIZE = 32  # Standard size for transfer learning; lower this to 16 if your computer runs out of memory

# Create DataLoaders
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, drop_last=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

# Initialize test dataset and dataloader
test_dataset = FGVCAircraftDataset(DATA_DIR, "images_variant_test.txt", class_to_idx, transform=val_transforms)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

print(f"Complete: DataLoaders created successfully.")
print(f" - Train batches: {len(train_loader)} (Total: {len(train_loader) * BATCH_SIZE} images)")
print(f" - Val batches: {len(val_loader)}")
print(f" - Test batches: {len(test_loader)}")

# Create the reverse lookup dictionary from your existing class_to_idx
idx_to_class = {idx: class_name for class_name, idx in class_to_idx.items()}

print(f"Reverse mapping created! Total classes available: {len(idx_to_class)}")
print(f"Example verification -> Index 0 maps to: {idx_to_class[0]}")

#Visualizing Augmented Samples From the DataLoader
# 1. Grab exactly one batch of 32 images from the training DataLoader
data_iter = iter(train_loader)
images, labels = next(data_iter)

# 2. Function to reverse ImageNet normalization so humans can view it
def imshow(img_tensor):
    # Convert from PyTorch tensor format (Channels, Height, Width) to Matplotlib format (Height, Width, Channels)
    np_img = img_tensor.numpy().transpose((1, 2, 0))

    # Reverse the ImageNet mean and std normalization math
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    np_img = std * np_img + mean

    # Clip pixel values so they stay strictly between 0 and 1
    np_img = np.clip(np_img, 0, 1)
    return np_img

# 3. Plot the first 5 images from this batch
plt.figure(figsize=(18, 4))
for i in range(5):
    plt.subplot(1, 5, i + 1)

    # Un-normalize and show the image
    plt.imshow(imshow(images[i]))

    # Get the text label from our previous idx_to_class dictionary
    class_name = idx_to_class[labels[i].item()]
    plt.title(f"Label: {class_name}", fontsize=10, fontweight='bold')
    plt.axis('off')

plt.tight_layout()
plt.show()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
weights = ResNet50_Weights.DEFAULT
model = resnet50(weights=weights)

for param in model.parameters():
    param.requires_grad = False

num_features = model.fc.in_features
model.fc = nn.Sequential(
    nn.Linear(num_features, 256),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(256, 100)

)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer= optim.Adam([
    {'params': model.fc.parameters(), 'lr': 1e-4},        # head trains faster
    {'params': model.layer4.parameters(), 'lr': 1e-5},    # fine-tune slowly
    {'params': model.layer3.parameters(), 'lr': 1e-5}
], weight_decay=1e-4)

print("Completed pretrained ResNet50 configured as a feature extractor")

EPOCHS = 10

print("Initiating training loop...")

history = {
    'train_loss': [],
    'train_acc': [],
    'val_loss': [],
    'val_acc': []
}

early_stop = EarlyStopping(patience=3, restore_best_weights=True)

for epoch in range(EPOCHS):
    start_time = time.time()

    # --- TRAINING PHASE ---
    model.train()
    train_loss = 0.0
    train_correct = 0
    total_train_samples = 0

    # Create the progress wrapper
    train_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS} [Training]")

    # FIX: Iterate directly over the train_bar wrapper!
    for images, labels in train_bar:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        train_loss += loss.item() * images.size(0)

        _, preds = torch.max(outputs, 1)
        train_correct += torch.sum(preds == labels.data)
        total_train_samples += images.size(0)

        # Update the live progress bar stats
        train_bar.set_postfix(batch_loss=f"{loss.item():.4f}")

    epoch_train_loss = train_loss / total_train_samples
    epoch_train_acc = (train_correct.double() / total_train_samples) * 100

    # --- VALIDATION PHASE ---
    model.eval()
    val_loss = 0.0
    val_correct = 0
    total_val_samples = 0

    val_bar = tqdm(val_loader, desc=f"Epoch {epoch+1}/{EPOCHS} [Validation]")

    with torch.no_grad():
        # FIX: Iterate directly over the val_bar wrapper!
        for images, labels in val_bar:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)

            val_loss += loss.item() * images.size(0)
            _, preds = torch.max(outputs, 1)
            val_correct += torch.sum(preds == labels.data)
            total_val_samples += images.size(0)

            # Update the live progress bar stats
            val_bar.set_postfix(batch_loss=f"{loss.item():.4f}")

    epoch_val_loss = val_loss / total_val_samples
    epoch_val_acc = (val_correct.double() / total_val_samples) * 100

    history['train_loss'].append(epoch_train_loss)
    history['train_acc'].append(epoch_train_acc)

    history['val_loss'].append(epoch_val_loss)
    history['val_acc'].append(epoch_val_acc)

    elapsed_time = time.time() - start_time
    print(f"\nEpoch {epoch+1}/{EPOCHS} Finised in [{elapsed_time:.1f}s] -> "
          f"Train Loss: {epoch_train_loss:.4f} | Train Acc: {epoch_train_acc:.2f}% | "
          f"Val Loss: {epoch_val_loss:.4f} | Val Acc: {epoch_val_acc:.2f}%\n" + "-"*60)

    early_stop(epoch_val_loss, model)

    if early_stop.early_stop:
      print(f"Early stopping triggered at epoch{epoch+1}")
      break


print("Baseline training test complete!")

torch.save(model.state_dict(), 'resnet50_frozen_baseline.pth')
print("Saved baseline weights!")

#fixing mapping
import os
import pickle

# Ensure DATA_DIR is defined (from your earlier walk)
if 'DATA_DIR' not in dir():
    for root, dirs, files in os.walk(path):
        if "variants.txt" in files:
            DATA_DIR = root
            break

# 1. Read class names in the EXACT order they appear in the file.
#    DO NOT SORT. This is the order the dataset loader used.
with open(os.path.join(DATA_DIR, 'variants.txt'), 'r') as f:
    class_names_ordered = [line.strip() for line in f.readlines()]

# 2. Build the mapping exactly as the model learned it (Index -> Name)
idx_to_class = {i: name for i, name in enumerate(class_names_ordered)}
class_to_idx = {name: i for i, name in idx_to_class.items()}

# 3. Save it so you never lose it again
with open('idx_to_class.pkl', 'wb') as f:
    pickle.dump(idx_to_class, f)

print("idx_to_class rebuilt successfully using the EXACT file order (NO SORTING)!")
print(f"Total classes: {len(idx_to_class)}")
print(f"Index 20 is now: {idx_to_class[20]}")
print(f"Finding '737-800':")
for idx, name in idx_to_class.items():
    if '737-800' in name:
        print(f"  '737-800' is at index {idx}")

# 1. Load the ResNet50 architecture with its pretrained weights
model = resnet50(weights=ResNet50_Weights.DEFAULT)

# 2. STEP 9: Freeze all pretrained layers
# This turns off gradient calculations for the entire base network

for param in model.parameters():
    param.requires_grad = False

# 3. STEP 10: Replace the final classifier
# ResNet50's final layer is named 'fc'. We extract its input size (2048 features)
num_features = model.fc.in_features

# Overwrite it with a brand new linear layer mapping to your 100 aircraft classes
# New layers automatically have requires_grad = True
model.fc = nn.Linear(num_features, 100)

# unfreezing layers 3 and 4
for param in model.layer3.parameters():
    param.requires_grad = True
for param in model.layer4.parameters():
    param.requires_grad = True

# 4. Push the updated model to your web Colab GPU
model = model.to(device)

# 5. CRITICAL: Tell the optimizer to ONLY track the new classifier parameters
# Passing model.parameters() here would waste memory tracking frozen layers
optimizer = optim.Adam([
    {'params': model.fc.parameters(), 'lr': 0.001},
    {'params': model.layer3.parameters(), 'lr': 1e-5 },
    {'params': model.layer4.parameters(), 'lr': 1e-5}
],weight_decay=1e-4)


criterion = nn.CrossEntropyLoss()

# Quick sanity check printout
print("Model Surgery Complete!")
print(f"Base layers frozen successfully.")
print(f"New classifier layer configured: Linear(in_features={num_features}, out_features=100)")
print(f"Trainable parameters: fc, layers3, layers4")

# Validating changes
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total = sum(p.numel() for p in model.parameters())
print(f"Trainable: {trainable:,} / Total: {total:,} parameters")

# Learning Rate Scheduler (correct spelling and syntax)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='min',
    factor=0.5,
    patience=3
)

print("Learning rate scheduler configured (ReduceLROnPlateau).")

# traning loop
epoch = 10
best_val_acc = 0.0

for epoch in range(epoch):

#traning phase
  model.train()
  train_loss - 0.0
  train_correct = 0
  train_total = 0

  for images, labels in train_loader:
   # move data to device (GPU or CPU)
    images, labels = images.to(device), labels.to(device)

#Zero the parameter gradients
    optimizer.zero_grad()

    # forward pass
    outputs = model(images)
    loss = criterion(outputs, labels)

#Backward pass and optimize
    loss.backward()
    optimizer.step()

#Track statistics
    train_loss += loss.item() * images.size(0)
    _, preds = torch.max(outputs, 1)
    train_total += images.size(0)
    train_correct += torch.sum(preds == labels.data)

  epoch_train_loss = train_loss / train_total
  epoch_train_acc = 100 * train_correct/ train_total

# Validation Phase
  model.eval()
  val_loss = 0.0
  val_correct = 0
  val_total = 0

  with torch.no_grad():
    for images, labels in val_loader:
      images, labels = images.to(device), labels.to(device)
      outputs = model(images)
      loss = criterion(outputs, labels)

      val_loss += loss.item() * images.size(0)
      _, preds = torch.max(outputs, 1)
      val_total += labels.size(0)
      val_correct += (preds == labels).sum().item()

  epoch_val_loss = val_loss / val_total
  epoch_val_acc = 100 * val_correct / val_total

  scheduler.step(epoch_val_loss)

  print(f"Epoch [{epoch+1}/{epoch}]")
  print(f"  Train Loss: {epoch_train_loss:.4f}, Train Acc: {epoch_train_acc:.2f}%")
  print(f"  Val Loss:   {epoch_val_loss:.4f}, Val Acc:   {epoch_val_acc:.2f}%")

  # get current learning rates for each group
  current_lrs = [group['lr'] for group in optimizer.param_groups]
  print (f"Current LRs: FC={current_lrs[0]:.2e}, Layer4={current_lrs[1]:.2e}, Layer3={current_lrs[2]:.2e}")

#save the best model
  if epoch_val_acc > best_val_acc:
    best_val_acc = epoch_val_acc
    torch.save(model.state_dict(),'best_resnet50_finetuned.pth')
    print(f"New best model saved! Acc: {best_val_acc:.2f}% ")

    print("-" * 50)

# TEST EVALUATION

model.load_state_dict(torch.load('best_resnet50_finetuned.pth', map_location=device))

# Ensure model is on the correct device and in eval mode
model = model.to(device)
model.eval()

test_loss = 0.0
test_correct = 0
test_total = 0

with torch.no_grad():
  for images, labels in test_loader:
    images, labels = images.to(device), labels.to(device)
    outputs = model(images)
    loss = criterion(outputs, labels)

    test_loss += loss.item() * images.size(0)
    _, preds = torch.max(outputs, 1)
    test_total += labels.size(0)
    test_correct += (preds == labels).sum().item()

  test_loss = test_loss / test_total
  test_acc = 100 * test_correct / test_total

  print(f"Test Loss: {test_loss:.4f}, Test Acc: {test_acc:.2f}%")

model.eval()
misclassified = []

# Optional: stop after collecting N misclassifications
MAX_SAMPLES = 50

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)

        probs = F.softmax(outputs, dim=1)
        confidences, preds = torch.max(probs, dim=1)

        for i in range(images.size(0)):
            if preds[i] != labels[i]:
                misclassified.append({
                    'image': images[i].cpu(),
                    'true_label': labels[i].item(),
                    'pred_label': preds[i].item(),
                    'confidence': confidences[i].item()
                })

        if len(misclassified) >= MAX_SAMPLES:
            break

print(f"Collected {len(misclassified)} misclassified samples.")   # <-- FIXED typo

# 2. Denormalize function
def denormalize(tensor):
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
    std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
    tensor = tensor * std + mean
    tensor = torch.clamp(tensor, 0, 1)
    return tensor.numpy().transpose(1, 2, 0)

# ----- 3. Plot misclassifications (up to 25) -----
num_plot = min(25, len(misclassified))
if num_plot == 0:
    print("No misclassified images found! (Perfect test set?)")
else:
    cols = 5
    rows = (num_plot + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(15, rows * 3))
    axes = axes.flatten()

    for idx in range(num_plot):
        sample = misclassified[idx]
        img_np = denormalize(sample['image'])

        ax = axes[idx]
        ax.imshow(img_np)
        ax.axis('off')

        true_name = idx_to_class[sample['true_label']]
        pred_name = idx_to_class[sample['pred_label']]
        conf = sample['confidence']

        ax.set_title(
            f"True: {true_name}\nPred: {pred_name} ({conf:.2f})",
            color='red',
            fontsize=9
        )

    # Hide unused subplots
    for idx in range(num_plot, len(axes)):
        axes[idx].axis('off')

    plt.tight_layout()
    plt.show()

# ----- 4. Summary stats -----
print("\n--- Misclassification Summary ---")
print(f"Total misclassified in this batch: {len(misclassified)}")
print(f"Showing {num_plot} of them.")

if len(misclassified) > 0:
    conf_list = [s['confidence'] for s in misclassified]
    print(f"Average confidence when wrong: {np.mean(conf_list):.3f}")
    print(f"Max confidence when wrong: {np.max(conf_list):.3f}")
    print(f"Min confidence when wrong: {np.min(conf_list):.3f}")

#confusion matrix

model.eval()
all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Confusion matrix (100x100)
cm = confusion_matrix(all_labels, all_preds)

# For readability, we'll show a heatmap of the most confused classes
# First, get per-class accuracies
class_acc = cm.diagonal() / cm.sum(axis=1)
worst_classes = np.argsort(class_acc)[:10]  # 10 worst performing classes

# Plot confusion matrix for just those worst classes (to zoom in)
plt.figure(figsize=(12, 10))
sns.heatmap(cm[worst_classes][:, worst_classes],
            annot=True, fmt='d', cmap='Blues',
            xticklabels=[idx_to_class[i] for i in worst_classes],
            yticklabels=[idx_to_class[i] for i in worst_classes])
plt.title('Confusion Matrix (Worst 10 Classes)')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

# Print the names of the worst classes
print("Worst performing classes:")
for idx in worst_classes:
    acc = class_acc[idx]
    print(f"{idx_to_class[idx]}: {acc*100:.2f}%")

target_classes = ['707-320', '727-200']
for target_name in target_classes:
    if target_name not in idx_to_class.values():
        print(f"'{target_name}' not found – check spelling")
        continue
    target_idx = list(idx_to_class.keys())[list(idx_to_class.values()).index(target_name)]
    true_mask = (all_labels == target_idx)
    if not np.any(true_mask):
        print(f"No test samples for {target_name}")
        continue
    preds_for = all_preds[true_mask]
    unique, counts = np.unique(preds_for, return_counts=True)
    sorted_pairs = sorted(zip(counts, unique), reverse=True)
    print(f"\n{target_name} (total {len(preds_for)} samples):")
    for count, pred_idx in sorted_pairs[:5]:
        pred_name = idx_to_class[pred_idx]
        correct = "✓" if pred_idx == target_idx else "✗"
        print(f"  {correct} -> {pred_name} : {count} times")

model.eval()
val_preds = []
val_labels = []

with torch.no_grad():
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, preds = torch.max(outputs, 1)
        val_preds.extend(preds.cpu().numpy())
        val_labels.extend(labels.cpu().numpy())

val_preds = np.array(val_preds)
val_labels = np.array(val_labels)

# Per-class accuracy on validation
val_class_acc = {}
for cls_idx in np.unique(val_labels):
    mask = (val_labels == cls_idx)
    correct = (val_preds[mask] == cls_idx).sum()
    total = mask.sum()
    acc = correct / total * 100
    class_name = idx_to_class[cls_idx]
    val_class_acc[class_name] = acc

# Show specific classes
for name in ['707-320', '727-200']:
    if name in val_class_acc:
        print(f"{name}: {val_class_acc[name]:.2f}%")
    else:
        print(f"{name} not in validation set.")

train_labels_all = []
for _, labels in train_loader:
  train_labels_all.extend(labels.cpu().numpy())
train_labels_all = np.array(train_labels_all)

classes = np.unique(train_labels_all)
class_weights = compute_class_weight('balanced', classes=classes, y=train_labels_all)
class_weights = torch.tensor(class_weights, dtype=torch.float).to(device)

model.load_state_dict(torch.load('best_resnet50_finetuned.pth', map_location=device))
model = model.to(device)

for param in model.layer2.parameters():
    param.requires_grad = True


print("Layer2 trainable:", any(p.requires_grad for p in model.layer2.parameters()))
print("Layer3 trainable:", any(p.requires_grad for p in model.layer3.parameters()))
print("Layer4 trainable:", any(p.requires_grad for p in model.layer4.parameters()))

#Setting up the new optimizer and criterion
criterion = nn.CrossEntropyLoss(weight=class_weights)

optimizer = optim.Adam([
    {'params' : model.fc.parameters(), 'lr': 1e-4},
    {'params': model.layer2.parameters(), 'lr': 1e-5},
    {'params': model.layer3.parameters(), 'lr': 1e-5},
    {'params': model.layer4.parameters(), 'lr': 1e-6}],
                       weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='min',
    factor=0.5,
    patience=3
)

EPOCHS_EX =10
best_val_acc = 0.0

for epoch in range(EPOCHS_EX):
  model.train()
  train_loss = 0.0
  train_correct = 0
  train_total = 0

  for images, labels in train_loader:
    images, labels = images.to(device), labels.to(device)
    optimizer.zero_grad()
    outputs = model(images)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()

    train_loss += loss.item() * images.size(0)
    _, preds = torch.max(outputs, 1)
    train_total += labels.size(0)
    train_correct += (preds == labels).sum().item()


    epoch_train_loss = train_loss / train_total
  epoch_train_acc = 100 * train_correct / train_total

  model.eval()
  val_loss = 0.0
  val_correct = 0
  val_total = 0

  with torch.no_grad():
    for images, labels in val_loader:
      images, labels = images.to(device), labels.to(device)
      outputs = model(images)
      loss = criterion(outputs, labels)

      val_loss += loss.item() * images.size(0)
      _, preds = torch.max(outputs, 1)
      val_total += labels.size(0)
      val_correct += (preds == labels).sum().item()

      epoch_val_loss = val_loss / val_total
  epoch_val_acc = 100 * val_correct / val_total

  scheduler.step(epoch_val_loss)
  print(f"Extra Epoch [{epoch+1}/{EPOCHS_EX}]")
  print(f"  Train Loss: {epoch_train_loss:.4f}, Train Acc: {epoch_train_acc:.2f}%")
  print(f"  Val Loss:   {epoch_val_loss:.4f}, Val Acc:   {epoch_val_acc:.2f}%")

if epoch_val_acc > best_val_acc:
    best_val_acc = epoch_val_acc
    torch.save(model.state_dict(),'best_resnet50_finetuned_extra.pth')
    print(f"  *** New best model saved! Acc: {best_val_acc:.2f}% ***")
    print("-" * 60)

model.load_state_dict(torch.load('best_resnet50_finetuned_extra.pth', map_location=device))
model = model.to(device)
model.eval()

test = 0.0
test_correct = 0
test_total = 0

with torch.no_grad():
  for images, labels in test_loader:
    images, labels = images.to(device), labels.to(device)
    outputs = model(images)
    loss = criterion(outputs, labels)

    test += loss.item() * images.size(0)
    _, preds = torch.max(outputs, 1)
    test_total += labels.size(0)
    test_correct += (preds == labels).sum().item()

test_loss = test_loss/test_total
test_acc = 100 * test_correct / test_total

print(f"Test Loss: {test_loss:.4f}, Test Acc: {test_acc:.2f}%")

print(f"Final Validation Acc: {best_val_acc:.2f}%")
print(f"Final Test Acc: {test_acc:.2f}%")

import os
pth_files = [f for f in os.listdir('.') if f.endswith('.pth')]
print("Available checkpoint files:")
for f in pth_files:
    print(f" - {f}")

#  Load the best final model
model.load_state_dict(torch.load('best_resnet50_finetuned_extra.pth', map_location=device))
model = model.to(device)
model.eval()

#  Helper function to get predictions
def get_predictions(loader):
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    return np.array(all_preds), np.array(all_labels)

# Get predictions for validation and test sets
val_preds, val_labels = get_predictions(val_loader)
test_preds, test_labels = get_predictions(test_loader)

#Function to print per‑class accuracy for specific classes
def print_class_accuracy(preds, labels, class_names, loader_name):
    print(f"\n{'='*20} {loader_name} {'='*20}")
    for name in class_names:
        if name not in idx_to_class.values():
            print(f"⚠️ '{name}' not found in idx_to_class")
            continue
        # Get index from name
        idx = list(idx_to_class.keys())[list(idx_to_class.values()).index(name)]
        mask = (labels == idx)
        if not np.any(mask):
            print(f"{name}: No samples in this set.")
            continue
        correct = (preds[mask] == idx).sum()
        total = mask.sum()
        acc = correct / total * 100
        print(f"{name}: {acc:.2f}% ({correct}/{total})")

# Check specific classes on validation (707-320 & 727-200)
print_class_accuracy(val_preds, val_labels, ['707-320', '727-200'], "VALIDATION SET")

# Check the previously worst test classes to see improvement
worst_previous = ['767-300', '747-100', 'A320', 'A340-300', '737-500',
                  '737-800', 'A310', 'DC-10', 'C-47', '737-700']
print_class_accuracy(test_preds, test_labels, worst_previous, "TEST SET")

# Overall worst 10 classes on test set (to see if new ones emerged)
# Compute per-class accuracy on test set
test_class_acc = {}
for cls_idx in np.unique(test_labels):
    mask = (test_labels == cls_idx)
    correct = (test_preds[mask] == cls_idx).sum()
    total = mask.sum()
    acc = correct / total * 100
    test_class_acc[cls_idx] = acc

# Get the 10 worst performing classes on test
sorted_test_acc = sorted(test_class_acc.items(), key=lambda x: x[1])
print("\n" + "="*20 + " WORST 10 TEST CLASSES (CURRENT) " + "="*20)
for cls_idx, acc in sorted_test_acc[:10]:
    name = idx_to_class[cls_idx]
    print(f"{name}: {acc:.2f}%")

import matplotlib.pyplot as plt
import torch

# Find the index of '737-800' in your idx_to_class
target_name = '737-800'
if target_name not in idx_to_class.values():
    print(f"'{target_name}' not found in idx_to_class")
else:
    target_idx = list(idx_to_class.keys())[list(idx_to_class.values()).index(target_name)]
    print(f"Index for {target_name}: {target_idx}")

    # Search through test_loader for an image of this class
    found = False
    for images, labels in test_loader:
        # Move to CPU for comparison
        labels_cpu = labels.cpu()
        mask = (labels_cpu == target_idx)
        if mask.any():
            # Take the first occurrence
            idx = torch.where(mask)[0][0].item()
            img_tensor = images[idx].unsqueeze(0).to(device)  # add batch dim
            true_label = labels[idx].item()
            found = True
            break

    if not found:
        print("No 737-800 images found in the test set.")
    else:
        # Run inference
        model.eval()
        with torch.no_grad():
            outputs = model(img_tensor)
            probs = torch.softmax(outputs, dim=1)
            top_probs, top_indices = torch.topk(probs, k=5)

        # Display the image (denormalize)
        def denormalize(tensor):
            mean = torch.tensor([0.485, 0.456, 0.406]).view(3,1,1)
            std = torch.tensor([0.229, 0.224, 0.225]).view(3,1,1)
            tensor = tensor.cpu() * std + mean
            return tensor.clamp(0,1).numpy().transpose(1,2,0)

        plt.figure(figsize=(6,6))
        plt.imshow(denormalize(img_tensor[0]))
        plt.axis('off')
        plt.title(f"True label: {idx_to_class[true_label]}")
        plt.show()

        print("Top‑5 predictions:")
        for i in range(5):
            idx = top_indices[0][i].item()
            name = idx_to_class[idx]
            conf = top_probs[0][i].item() * 100
            print(f"  {i+1}. {name} ({conf:.2f}%)")

!pip install gradio -q

import gradio as gr
import torch
from PIL import Image as PILImage
from torchvision import transforms
import numpy as np

# ----- Ensure the model is loaded -----
try:
    model
except NameError:
    model.load_state_dict(torch.load('best_resnet50_finetuned_extra.pth', map_location=device))
    model = model.to(device)
model.eval()

# ----- Preprocessing -----
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# ----- Prediction function (returns dict for gr.Label) -----
def predict_top1(image):
    img_pil = PILImage.fromarray(image.astype('uint8')).convert('RGB')
    img_tensor = transform(img_pil).unsqueeze(0).to(device)

    with torch.no_grad():
        outputs = model(img_tensor)
        probs = torch.softmax(outputs, dim=1)
        top_prob, top_idx = torch.max(probs, dim=1)

    class_name = idx_to_class[top_idx.item()]
    confidence = top_prob.item()

    # Return as a dictionary (class name -> confidence)
    return {class_name: confidence}

# ----- Create the interface -----
iface = gr.Interface(
    fn=predict_top1,
    inputs=gr.Image(type="numpy", label="📤 Upload Aircraft Image"),
    outputs=gr.Label(label="🏆 Top Prediction", num_top_classes=1),
    title="✈️ Aircraft Variant Classifier",
    description="Upload a side‑profile photo of an aircraft. The model will identify the exact variant.",
    flagging_mode="never"
)

# Launch (share=True gives a public link)
iface.launch(share=True, debug=True)

# Print all class names from idx_to_class (training order)
print("All 100 aircraft classes in the training set (in index order):\n")
for idx, name in idx_to_class.items():
    print(f"{idx:3d}: {name}")

with torch.no_grad():
    outputs = model(img_tensor)
    probs = torch.softmax(outputs, dim=1)
    top_probs, top_indices = torch.topk(probs, k=5)

print("Top‑5 predictions:")
for i in range(5):
    idx = top_indices[0][i].item()
    name = idx_to_class[idx]
    conf = top_probs[0][i].item() * 100
    print(f"  {i+1}. {name} ({conf:.2f}%)")

import matplotlib.pyplot as plt
import torch
from PIL import Image
from google.colab import files

# ----- 1. Re-upload the image (or use the one you already have) -----
uploaded = files.upload()
filename = list(uploaded.keys())[0]
img = Image.open(filename).convert('RGB')

# ----- 2. Preprocess -----
img_tensor = transform(img).unsqueeze(0).to(device)

# ----- 3. Predict -----
model.eval()
with torch.no_grad():
    outputs = model(img_tensor)
    probs = torch.softmax(outputs, dim=1)
    top_probs, top_indices = torch.topk(probs, k=5)

# ----- 4. Display the image and predictions -----
def denormalize(tensor):
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3,1,1)
    std = torch.tensor([0.229, 0.224, 0.225]).view(3,1,1)
    tensor = tensor.cpu() * std + mean
    return tensor.clamp(0,1).numpy().transpose(1,2,0)

plt.figure(figsize=(6,6))
plt.imshow(denormalize(img_tensor[0]))
plt.axis('off')
plt.title(f"Uploaded Image: {filename}")
plt.show()

print("Top‑5 predictions:")
for i in range(5):
    idx = top_indices[0][i].item()
    name = idx_to_class[idx]
    conf = top_probs[0][i].item() * 100
    print(f"  {i+1}. {name} ({conf:.2f}%)")